### ISSUE TITLE
Rakarrack-plus hangs after restart if a dialog has been resized.

### ISSUE THREAD

**Issue by ycollet** [Stazed/rakarrack-plus#52]
Using last version of rakarrack-plus 1.2.6 on Fedora 41.
I think the hangs is due to window resize, and then a font size problem.
Here is the stack trace:
```
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007ffff6c7ed03 in __pthread_kill_internal (threadid=<optimized out>, signo=6) at pthread_kill.c:78
#2  0x00007ffff6c25d1e in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff6c0d942 in __GI_abort () at abort.c:79
#4  0x00007ffff6c0e7a7 in __libc_message_impl (fmt=fmt@entry=0x7ffff6dc13cd "%s\n") at ../sysdeps/posix/libc_fatal.c:132
#5  0x00007ffff6c88e25 in malloc_printerr (str=str@entry=0x7ffff6dbf0c2 "corrupted double-linked list") at malloc.c:5772
#6  0x00007ffff6c898ac in unlink_chunk (p=p@entry=0x555556ce7bc0, av=0x7ffff6df6ac0 <main_arena>) at malloc.c:1617
#7  0x00007ffff6c8c81a in _int_malloc (av=av@entry=0x7ffff6df6ac0 <main_arena>, bytes=bytes@entry=8) at malloc.c:4381
#8  0x00007ffff6c8d4b4 in __GI___libc_malloc (bytes=bytes@entry=8) at malloc.c:3336
#9  0x00007ffff6c941af in __GI___strdup (s=0x555555c3de80 "cursive") at strdup.c:42
#10 0x00007ffff70883c1 in IA__FcValueSave (v=...) at /usr/src/debug/fontconfig-2.15.0-8.fc41.x86_64/src/fcpat.c:103
#11 FcConfigEvaluate (p=p@entry=0x555556e10f00, p_pat=p_pat@entry=0x0, kind=kind@entry=FcMatchPattern, e=<optimized out>)
    at /usr/src/debug/fontconfig-2.15.0-8.fc41.x86_64/src/fccfg.c:1233
#12 0x00007ffff708d505 in FcConfigMatchValueList (p=0x555556e10f00, p_pat=<optimized out>, kind=<optimized out>, t=<optimized out>, values=0x555556ce3cb0, 
    table=0x7fffffd5c9f0) at /usr/src/debug/fontconfig-2.15.0-8.fc41.x86_64/src/fccfg.c:1702
#13 IA__FcConfigSubstituteWithPat (config=<optimized out>, config@entry=0x0, p=p@entry=0x555556e10f00, p_pat=p_pat@entry=0x0, kind=kind@entry=FcMatchPattern)
    at /usr/src/debug/fontconfig-2.15.0-8.fc41.x86_64/src/fccfg.c:2151
#14 0x00007ffff708df99 in IA__FcConfigSubstituteWithPat (config=<optimized out>, p=<optimized out>, p_pat=<optimized out>, kind=<optimized out>)
    at /usr/src/debug/fontconfig-2.15.0-8.fc41.x86_64/src/fccfg.c:2292
#15 0x00007ffff70e3bb3 in XftFontMatch (dpy=0x555555bd17e0, screen=0, pattern=<optimized out>, result=0x7fffffd5cad0)
    at /usr/src/debug/libXft-2.3.8-7.fc41.x86_64/src/xftfont.c:46
#16 0x00007ffff7f16988 in fontopen (core=false, name=<optimized out>, size=<optimized out>, angle=<optimized out>)
    at /usr/src/debug/fltk-1.3.8-10.fc41.x86_64/src/fl_font_xft.cxx:239
#17 Fl_Font_Descriptor::Fl_Font_Descriptor (this=<optimized out>, name=<optimized out>, fsize=<optimized out>, fangle=<optimized out>, this=<optimized out>, 
    name=<optimized out>, fsize=<optimized out>, fangle=<optimized out>) at /usr/src/debug/fltk-1.3.8-10.fc41.x86_64/src/fl_font_xft.cxx:336
#18 0x00007ffff7f16df4 in fl_xft_font (driver=0x555555a5c560, fnum=<optimized out>, size=15, angle=0)
    at /usr/src/debug/fltk-1.3.8-10.fc41.x86_64/src/fl_font_xft.cxx:125
#19 0x00007ffff7ea0c27 in fl_font (face=<optimized out>, fsize=<optimized out>) at /usr/src/debug/fltk-1.3.8-10.fc41.x86_64/FL/fl_draw.H:509
#20 Fl_Browser::item_height (this=0x555556da2420, item=<optimized out>) at /usr/src/debug/fltk-1.3.8-10.fc41.x86_64/src/Fl_Browser.cxx:402
#21 Fl_Browser::item_height (this=0x555556da2420, item=0x555556e10e60) at /usr/src/debug/fltk-1.3.8-10.fc41.x86_64/src/Fl_Browser.cxx:363
#22 0x00007ffff7ea782f in Fl_Browser::insert (this=0x555556da2420, this@entry=0x555555c17510, line=1, line@entry=21845, item=0x555556e10e60)
    at /usr/src/debug/fltk-1.3.8-10.fc41.x86_64/src/Fl_Browser.cxx:269
#23 0x00007ffff7ea7973 in Fl_Browser::insert (this=0x555555c17510, line=21845, newtext=<optimized out>, d=d@entry=0x0)
    at /usr/src/debug/fltk-1.3.8-10.fc41.x86_64/src/Fl_Browser.cxx:295
#24 0x00007ffff7ea79ab in Fl_Browser::add (this=<optimized out>, newtext=<optimized out>, d=d@entry=0x0)
    at /usr/src/debug/fltk-1.3.8-10.fc41.x86_64/src/Fl_Browser.cxx:711
#25 0x000055555589de79 in RKRGUI::Prepare_Order (this=0x555556d12880) at /usr/src/debug/rakarrack-plus-1.2.6-2.fc41.x86_64/src/UI/rkrprocess_gui.cxx:2948
#26 0x000055555585533b in RKRGUI::cb_Preset_Counter_i (this=0x555556d12880, o=0x555556da0da0)
    at /usr/src/debug/rakarrack-plus-1.2.6-2.fc41.x86_64/src/UI/rakarrack.cxx:819
#27 RKRGUI::cb_Preset_Counter (o=0x555556da0da0, v=<optimized out>) at /usr/src/debug/rakarrack-plus-1.2.6-2.fc41.x86_64/src/UI/rakarrack.cxx:826
#28 0x00007ffff7f02d1a in Fl_Widget::do_callback (this=0x555556da0da0, o=0x555556da0da0, arg=0x5b) at /usr/src/debug/fltk-1.3.8-10.fc41.x86_64/src/Fl_Widget.cxx:348
#29 0x000055555589a71f in Fl_Widget::do_callback (this=<optimized out>, this=<optimized out>) at /usr/include/FL/Fl_Widget.H:861
#30 RKRGUI::load_previous_state (this=0x555556d12880) at /usr/src/debug/rakarrack-plus-1.2.6-2.fc41.x86_64/src/UI/rkrprocess_gui.cxx:793
--Type <RET> for more, q to quit, c to continue without paging--
#31 0x0000555555849274 in RKRGUI::RKRGUI (this=0x555556d12880, argc=1, argv=0x7fffffffd9e8, rkr_=0x7fffffe67c20)
    at /usr/src/debug/rakarrack-plus-1.2.6-2.fc41.x86_64/src/UI/rkrprocess_gui.cxx:111
#32 main (argc=1, argv=0x7fffffffd9e8) at /usr/src/debug/rakarrack-plus-1.2.6-2.fc41.x86_64/src/main.C:417
```

**Comment by ycollet** [comment]
Removed ".fltk/github.com.Stazed.rakarrack.plus/rakarrack-plus.prefs" and the problem is still here.
Don't know what triggered the problem ...

**Comment by ycollet** [comment]
Works fine again after a reboot.
I think the problem has been triggered by a nvidia driver update. After a reboot (first reboot after the update) everything is back.

**Comment by Stazed** [comment]
Glad it's working again, closing this then...
